# Generated by Django 5.1.3 on 2024-11-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hire_data',
            new_name='hire_date',
        ),
    ]
